on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: ${{ secrets.USERNAME }},
            repo: ${{ secrets.REPO }},
            workflow_id: 'repo-sync.yml',
            ref: 'main'
          })
